export const FLV_COPY = {
  brand: 'Fashion Leader Vote',
  brandMark: 'FLV',
  heroEyebrow: 'Fashion design, reimagined.',
  heroHeadline: 'Design fashion. See it instantly.',
  heroHeadlineAccent: 'Lead the future.',
  heroLead:
    'One connected house: cut the garment, draw all four sides, try it on, and enter the vote.',
  openStudio: 'Start creating',
  joinWaitlist: 'Join the waitlist',
  login: 'Login',
  possibilities: 'Possibilities',
  navProduct: 'Product',
  navHowItWorks: 'How it works',
  navCommunity: 'Community',
  navAbout: 'About',
  verticalLead: 'Design',
  verticalCreate: 'Create',
  verticalShare: 'Share',
  verticalLeadWord: 'Lead',
  verticalFooterFashion: 'Fashion',
  verticalFooterTech: 'Technology',
  verticalFooterPeople: 'People',
  verticalFooterImpact: 'Impact',
  statWaitlist: '10K+ Designers on the waitlist',
  statRealtime: '3D Real-time Visualization',
  statInfinite: 'Infinite Possibilities',
  stageGarment: 'Garment',
  stageDesign: 'Design',
  stageTryShare: 'Try on & share',
  flowTitle: 'Three steps. One seamless flow.',
  flowLead: 'Same garment. Live at every step.',
  flowGarmentLead: 'Choose a silhouette and cut. Bring ideas to life.',
  flowDesignLead: 'Draw freely. Tech refine. See every side live.',
  flowTryShareLead: 'Try it on. Capture media. Enter the board.',
  openInStudio: 'Open in studio',
  selectTitle: 'Choose your garment',
  selectLead: 'Pick a house silhouette and see it seated live.',
  selectCategoryTops: 'Tops',
  selectCategoryBottoms: 'Bottoms',
  selectCategoryOuterwear: 'Outerwear',
  selectCategoryAccessories: 'Accessories',
  selectDetails: 'Garment details',
  selectUse: 'Use this garment',
  fitTitle: 'Cut the garment',
  fitLead: 'Neck, hem, and sleeve change the cloth — not the body.',
  colorTitle: 'Color & pattern',
  colorLead: 'Cloth color, pattern fills, and finish on the live tee.',
  colorMaterial: 'Material details',
  designTitle: 'Four sides, one look',
  designLead: 'Front, back, left, and right beside live 3D.',
  designLayerDraw: 'Layer 1 Draw',
  designLayerTech: 'Layer 2 Tech design',
  designLayerPreview: 'Layer 3 3D Preview',
  designLive: 'Live',
  designLiveSync: 'Real-time sync — design updates instantly.',
  previewTitle: 'Try it on',
  previewLead: 'Avatar fit and camera angles before you share.',
  previewLive: 'Live 3D fit preview',
  shareTitle: 'Publish to community',
  shareLead: 'Angle stills, tags, and method — then enter the vote.',
  sharePublish: 'Publish to community',
  voteTitle: 'Top designs',
  voteLead: 'The most inspiring looks from the house.',
  seeBoard: 'See the board',
  soonTitle: 'Coming soon',
  soonAiShoot: 'AI shoot',
  soonAiShootLead:
    'Choose a preset, tune the shoot, and preview canned stills. Generation is not built yet.',
  soonAiVideo: 'AI fashion video',
  soonAiVideoLead:
    'Build a short reel from scenes and settings. Motion generation is not built yet.',
  soonBadge: 'Soon',
  shootPresets: 'AI shoot presets',
  shootPresetsLead: 'Choose a style. Set the mood. Preview stunning visuals.',
  shootConfig: 'Shoot configuration',
  shootGenerate: 'Generate model shoot',
  shootResults: 'AI generated results',
  shootResultsLead: 'High-end visuals for your brand, campaign, or social.',
  shootCustom: 'Custom style',
  videoScenes: 'Video scenes',
  videoAddScene: 'Add scene',
  videoTitle: 'Create AI fashion video',
  videoLead: 'Generated from your virtual model shoot.',
  videoSettings: 'Video settings',
  videoGenerate: 'Generate video',
  videoExport: 'Export presets',
  waitlistTitle: 'Early access',
  waitlistLead: 'Join the waitlist today. Get 6 months of free access.',
  waitlistOffer: '6 months free access',
  waitlistEmailOnly: 'Only your email required.',
  waitlistBenefitPackages: 'All software packages included',
  waitlistBenefitNoPayment: 'No payment required',
  waitlistBenefitNoSub: 'No automatic subscription',
  waitlistBenefitExpires: 'Access expires automatically',
  getEarlyAccess: 'Get early access',
} as const
