export const FLV_COPY = {
  brand: 'Fashion Leader Vote',
  heroHeadline: 'Design fashion. See it instantly. Lead the future.',
  heroLead:
    'One connected house: cut the garment, draw all four sides, try it on, and enter the vote.',
  openStudio: 'Open the studio',
  joinWaitlist: 'Join the waitlist',
  possibilities: 'Possibilities',
  stageGarment: 'Garment',
  stageDesign: 'Design',
  stageTryShare: 'Try on & share',
  openInStudio: 'Open in studio',
  selectTitle: 'Start with the form',
  selectLead: 'Pick a house silhouette and see it seated live.',
  fitTitle: 'Cut the garment',
  fitLead: 'Neck, hem, and sleeve change the cloth — not the body.',
  colorTitle: 'One color system',
  colorLead: 'Cloth color, pattern fills, and finish on the live tee.',
  designTitle: 'Four sides, one look',
  designLead: 'Front, back, left, and right beside live 3D.',
  previewTitle: 'Try it on',
  previewLead: 'Avatar fit and camera angles before you share.',
  shareTitle: 'Media before enter',
  shareLead: 'Angle stills, tags, and method — then enter the vote.',
  voteTitle: 'The board',
  voteLead: 'Rankings, filters, and a Leader the house can see.',
  seeBoard: 'See the board',
  soonTitle: 'Coming soon',
  soonAiShoot: 'AI shoot',
  soonAiShootLead: 'Presentation stills from the look. Not built yet.',
  soonAiVideo: 'AI fashion video',
  soonAiVideoLead: 'Short motion from the same design. Not built yet.',
  soonBadge: 'Soon',
  waitlistTitle: 'Join the house',
  waitlistLead: 'Early access when the next room opens.',
} as const
