export const HOUSE_COPY = {
  lookGone: 'That look has left the house.',
  lookFailed: 'The look could not open.',
  boardFailed: 'The board could not open.',
  boardLoading: 'The house is setting the board.',
  lookLoading: 'Opening the look.',
  entered: 'Entered the vote',
  entering: 'Entering the vote',
  enter: 'Enter the Vote',
  studioOpen: 'The studio is open.',
  voteFailed: 'The vote could not be counted.',
  copyFailed: 'The link could not be copied. Use the address bar.',
  publishFailed: 'The look could not enter the vote.',
  boardFull: 'The house is full tonight.',
  boardPersistFailed: 'The look could not be kept. Try again.',
  gownCredit: 'Gown by Style3D CG',
  gownLicense: 'CC BY 4.0',
  draw: 'Draw',
  cloth: 'Cloth',
  front: 'Front',
  back: 'Back',
  sleeve: 'Sleeve',
  cropHem: 'Crop',
  longHem: 'Long',
  shortSleeve: 'Short',
  longSleeve: 'Long',
  stripe: 'Stripe',
  check: 'Check',
  thisHouse: 'This house',
  brush: 'Brush',
  erase: 'Erase',
  clearInk: 'Clear',
  artwork: 'Artwork',
  type: 'Type',
  morning: 'Keep this morning',
  restoreMorning: 'Morning',
  join: 'Join the house',
  joining: 'Joining',
  joined: 'You are on the list.',
  waitlistFailed: 'The list could not take that address.',
  waitlistBusy: 'The list is busy. Try again shortly.',
  inkTooHeavy: 'The mark is too heavy for the board.',
  artworkHeavy: 'That artwork is too heavy.',
  soonLead: 'Create a look. Show it. See if it leads.',
  onTheCloth: 'On the cloth',
  hideLayer: 'Hide',
  showLayer: 'Show',
  dismissLayer: 'Dismiss',
  displayFace: 'Display',
  sansFace: 'Sans',
} as const

export const GOWN_CREDIT_HREF =
  'https://sketchfab.com/3d-models/white-evening-gown-dress-1f77c65b1542428f89b10f538b771ce4'
export const GOWN_LICENSE_HREF = 'https://creativecommons.org/licenses/by/4.0/'

export function remixCaption({ title }: { title: string }) {
  return `Remixing ${title}`
}
