/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as LookLookIdRouteImport } from './routes/look.$lookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const LookLookIdRoute = LookLookIdRouteImport.update({
  id: '/look/$lookId',
  path: '/look/$lookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vote': typeof VoteRoute
  '/look/$lookId': typeof LookLookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vote': typeof VoteRoute
  '/look/$lookId': typeof LookLookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vote': typeof VoteRoute
  '/look/$lookId': typeof LookLookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vote' | '/look/$lookId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vote' | '/look/$lookId'
  id: '__root__' | '/' | '/vote' | '/look/$lookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VoteRoute: typeof VoteRoute
  LookLookIdRoute: typeof LookLookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/look/$lookId': {
      id: '/look/$lookId'
      path: '/look/$lookId'
      fullPath: '/look/$lookId'
      preLoaderRoute: typeof LookLookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VoteRoute: VoteRoute,
  LookLookIdRoute: LookLookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
